version: '3.8'
services:
 bitcoin-core:
  image: ruimarinho/bitcoin-core:23.0
  container_name: bitcoind
  restart: unless-stopped
  command:
   -printtoconsole
   -conf=/home/bitcoin/conf/bitcoin.conf
  ports:
   - "8332:8332"
   - "28332:28332"
   - "8333:8333"
  volumes:
   - ./data:/home/bitcoin/.bitcoin
   - ./conf:/home/bitcoin/conf

 Fulcrum:
  image: cculianu/fulcrum:v1.9.0
  container_name: Fulcrum
  depends_on: 
   - bitcoin-core
  #restart: unless-stopped
  command: Fulcrum --ssl 0.0.0.0:50002
                   --tcp 0.0.0.0:50001
                   --bitcoind bitcoind:8332
                   --rpcuser foo
                   --rpcpassword bar
                   --fast-sync 0
  volumes:
   - ./fulcrum-data:/data
  ports:
   - 127.0.0.1:50001:50001
   - 50002:50002

