version: "3.8"

services:
  web:
    environment:
      FRONTEND_HTTP_PORT: "8080"
      BACKEND_MAINNET_HTTP_HOST: "api"
      LIGHTNING: "true"
    image: mempool/frontend:latest
    container_name: mempool.web
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    ports:
      - 80:8080
  api:
    environment:
      MEMPOOL_BACKEND: "electrum"
      ELECTRUM_HOST: "host.docker.internal"
      ELECTRUM_PORT: "50001"
      ELECTRUM_TLS_ENABLED: "false"
      #MEMPOOL_BACKEND: "none"
      CORE_RPC_HOST: "host.docker.internal"
      CORE_RPC_PORT: "8332"
      CORE_RPC_USERNAME: "foo"
      CORE_RPC_PASSWORD: "bar"
      SECOND_CORE_RPC_HOST: "host.docker.internal"
      SECOND_CORE_RPC_PORT: "8332"
      SECOND_CORE_RPC_USERNAME: "foo"
      SECOND_CORE_RPC_PASSWORD: "bar"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: "db"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      STATISTICS_ENABLED: "true"
      LIGHTNING_ENABLED: "true"
      LIGHTNING_BACKEND: "lnd"
      LIGHTNING_TOPOLOGY_FOLDER: "/backend/cache/topology"
      LIGHTNING_STATS_REFRESH_INTERVAL: 600
      LIGHTNING_GRAPH_REFRESH_INTERVAL: 600
      LIGHTNING_LOGGER_UPDATE_INTERVAL: 30
      # NODE_EXTRA_CA_CERTS: ""
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      LND_TLS_CERT_PATH: "/backend/.lnd/tls.cert"
      LND_MACAROON_PATH: "/backend/.lnd/data/chain/bitcoin/mainnet/readonly.macaroon"
      LND_REST_API_URL: "https://host.docker.internal:8080"
    image: mempool/backend:latest
    container_name: mempool.api
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for-it.sh db:3306 --timeout=720 --strict -- ./start.sh"
    volumes:
      - ../lnd:/backend/.lnd:ro
      - ./data:/backend/cache
  db:
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "admin"
    image: mariadb:10.5.8
    container_name: mempool.db
    # user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ./mysql/data:/var/lib/mysql

